# Description
description "This is a basic WordPress theme configured to use Foundation with Sass"

# Auto discover directories
discover :directories

file 'admin/assets/css/admin-style.css'
file 'admin/assets/css/colorpicker.css'

file 'admin/assets/images/colorpicker/blank.gif'
file 'admin/assets/images/colorpicker/colorpicker_background.png'
file 'admin/assets/images/colorpicker/colorpicker_hex.png'
file 'admin/assets/images/colorpicker/colorpicker_hsb_b.png'
file 'admin/assets/images/colorpicker/colorpicker_hsb_h.png'
file 'admin/assets/images/colorpicker/colorpicker_hsb_s.png'
file 'admin/assets/images/colorpicker/colorpicker_indic.gif'
file 'admin/assets/images/colorpicker/colorpicker_overlay.png'
file 'admin/assets/images/colorpicker/colorpicker_rgb_b.png'
file 'admin/assets/images/colorpicker/colorpicker_rgb_g.png'
file 'admin/assets/images/colorpicker/colorpicker_rgb_r.png'
file 'admin/assets/images/colorpicker/colorpicker_select.gif'
file 'admin/assets/images/colorpicker/colorpicker_submit.png'
file 'admin/assets/images/colorpicker/select.png'

file 'admin/assets/images/1col.png'
file 'admin/assets/images/2-col-portfolio.png'
file 'admin/assets/images/2cl.png'
file 'admin/assets/images/2cr.png'
file 'admin/assets/images/3-col-portfolio.png'
file 'admin/assets/images/3cm.png'
file 'admin/assets/images/3cr.png'
file 'admin/assets/images/4-col-portfolio.png'
file 'admin/assets/images/accept.png'
file 'admin/assets/images/button_check.png'
file 'admin/assets/images/dropdown-arrow.png'
file 'admin/assets/images/favicon.ico'
file 'admin/assets/images/icon_option.png'
file 'admin/assets/images/icon-add.png'
file 'admin/assets/images/icon-backup.png'
file 'admin/assets/images/icon-delete.png'
file 'admin/assets/images/icon-docs.png'
file 'admin/assets/images/icon-edit.png'
file 'admin/assets/images/icon-home.png'
file 'admin/assets/images/icon-info.png'
file 'admin/assets/images/icon-notice.png'
file 'admin/assets/images/icon-paint.png'
file 'admin/assets/images/icon-settings.png'
file 'admin/assets/images/icon-slider.png'
file 'admin/assets/images/icon-warn.png'
file 'admin/assets/images/loading-bottom.gif'
file 'admin/assets/images/select.png'
file 'admin/assets/images/sign_warning.png'
file 'admin/assets/images/stop.png'
file 'admin/assets/images/toggle_tabs.png'
file 'admin/assets/images/ui-bg_flat_0_aaaaaa_40x100.png'
file 'admin/assets/images/warning.png'
file 'admin/assets/images/wrench.png'
file 'admin/assets/images/wrench16.png'

file 'admin/assets/js/ajaxupload.js'
file 'admin/assets/js/colorpicker.js'
file 'admin/assets/js/cookie.js'
file 'admin/assets/js/jquery.maskedinput-1.2.2.js'
file 'admin/assets/js/jquery.tipsy.js'
file 'admin/assets/js/of-medialibrary-uploader.js'
file 'admin/assets/js/smof.js'

file 'admin/classes/class.options-machine.php'

file 'admin/front-end/options.php'

file 'admin/functions/functions.admin.php'
file 'admin/functions/functions.interface.php'
file 'admin/functions/functions.load.php'
file 'admin/functions/functions.mediauploader.php'
file 'admin/functions/functions.options.php'
file 'admin/functions/functions.php'

file 'admin/layouts/default.css'
file 'admin/layouts/placebo.css'

file 'admin/index.php'
file 'admin/README.txt'

file 'images/bg/bg0.png'
file 'images/bg/bg1.png'
file 'images/bg/bg2.png'
file 'images/bg/bg3.png'
file 'images/bg/bg4.png'
file 'images/bg/bg5.png'
file 'images/bg/bg6.jpg'
file 'images/bg/bg7.jpg'
file 'images/bg/bg8.png'
file 'images/bg/bg9.png'
file 'images/bg/bg10.png'
file 'images/bg/bg11.png'

file 'images/fairhead-icons/fc-webicon-behance-m.png'
file 'images/fairhead-icons/fc-webicon-behance-s.png'
file 'images/fairhead-icons/fc-webicon-behance.png'
file 'images/fairhead-icons/fc-webicon-behance.svg'
file 'images/fairhead-icons/fc-webicon-creativecloud-m.png'
file 'images/fairhead-icons/fc-webicon-creativecloud-s.png'
file 'images/fairhead-icons/fc-webicon-creativecloud.png'
file 'images/fairhead-icons/fc-webicon-creativecloud.svg'
file 'images/fairhead-icons/fc-webicon-dribbble-m.png'
file 'images/fairhead-icons/fc-webicon-dribbble-s.png'
file 'images/fairhead-icons/fc-webicon-dribbble.png'
file 'images/fairhead-icons/fc-webicon-dribbble.svg'
file 'images/fairhead-icons/fc-webicon-dropbox-m.png'
file 'images/fairhead-icons/fc-webicon-dropbox-s.png'
file 'images/fairhead-icons/fc-webicon-dropbox.png'
file 'images/fairhead-icons/fc-webicon-dropbox.svg'
file 'images/fairhead-icons/fc-webicon-evernote-m.png'
file 'images/fairhead-icons/fc-webicon-evernote-s.png'
file 'images/fairhead-icons/fc-webicon-evernote.png'
file 'images/fairhead-icons/fc-webicon-evernote.svg'
file 'images/fairhead-icons/fc-webicon-facebook-m.png'
file 'images/fairhead-icons/fc-webicon-facebook-s.png'
file 'images/fairhead-icons/fc-webicon-facebook.png'
file 'images/fairhead-icons/fc-webicon-facebook.svg'
file 'images/fairhead-icons/fc-webicon-flickr-m.png'
file 'images/fairhead-icons/fc-webicon-flickr-s.png'
file 'images/fairhead-icons/fc-webicon-flickr.png'
file 'images/fairhead-icons/fc-webicon-flickr.svg'
file 'images/fairhead-icons/fc-webicon-github-m.png'
file 'images/fairhead-icons/fc-webicon-github-s.png'
file 'images/fairhead-icons/fc-webicon-github.png'
file 'images/fairhead-icons/fc-webicon-github.svg'
file 'images/fairhead-icons/fc-webicon-googleplus-m.png'
file 'images/fairhead-icons/fc-webicon-googleplus-s.png'
file 'images/fairhead-icons/fc-webicon-googleplus.png'
file 'images/fairhead-icons/fc-webicon-googleplus.svg'
file 'images/fairhead-icons/fc-webicon-icloud-m.png'
file 'images/fairhead-icons/fc-webicon-icloud-s.png'
file 'images/fairhead-icons/fc-webicon-icloud.png'
file 'images/fairhead-icons/fc-webicon-icloud.svg'
file 'images/fairhead-icons/fc-webicon-linkedin-m.png'
file 'images/fairhead-icons/fc-webicon-linkedin-s.png'
file 'images/fairhead-icons/fc-webicon-linkedin.png'
file 'images/fairhead-icons/fc-webicon-linkedin.svg'
file 'images/fairhead-icons/fc-webicon-mail-m.png'
file 'images/fairhead-icons/fc-webicon-mail-s.png'
file 'images/fairhead-icons/fc-webicon-mail.png'
file 'images/fairhead-icons/fc-webicon-mail.svg'
file 'images/fairhead-icons/fc-webicon-msn-m.png'
file 'images/fairhead-icons/fc-webicon-msn-s.png'
file 'images/fairhead-icons/fc-webicon-msn.png'
file 'images/fairhead-icons/fc-webicon-msn.svg'
file 'images/fairhead-icons/fc-webicon-pinterest-m.png'
file 'images/fairhead-icons/fc-webicon-pinterest-s.png'
file 'images/fairhead-icons/fc-webicon-pinterest.png'
file 'images/fairhead-icons/fc-webicon-pinterest.svg'
file 'images/fairhead-icons/fc-webicon-rdio-m.png'
file 'images/fairhead-icons/fc-webicon-rdio-s.png'
file 'images/fairhead-icons/fc-webicon-rdio.png'
file 'images/fairhead-icons/fc-webicon-rdio.svg'
file 'images/fairhead-icons/fc-webicon-rss-m.png'
file 'images/fairhead-icons/fc-webicon-rss-s.png'
file 'images/fairhead-icons/fc-webicon-rss.png'
file 'images/fairhead-icons/fc-webicon-rss.svg'
file 'images/fairhead-icons/fc-webicon-skitch-m.png'
file 'images/fairhead-icons/fc-webicon-skitch-s.png'
file 'images/fairhead-icons/fc-webicon-skitch.png'
file 'images/fairhead-icons/fc-webicon-skitch.svg'
file 'images/fairhead-icons/fc-webicon-skype-m.png'
file 'images/fairhead-icons/fc-webicon-skype-s.png'
file 'images/fairhead-icons/fc-webicon-skype.png'
file 'images/fairhead-icons/fc-webicon-skype.svg'
file 'images/fairhead-icons/fc-webicon-spotify-m.png'
file 'images/fairhead-icons/fc-webicon-spotify-s.png'
file 'images/fairhead-icons/fc-webicon-spotify.png'
file 'images/fairhead-icons/fc-webicon-spotify.svg'
file 'images/fairhead-icons/fc-webicon-stumbleupon-m.png'
file 'images/fairhead-icons/fc-webicon-stumbleupon-s.png'
file 'images/fairhead-icons/fc-webicon-stumbleupon.png'
file 'images/fairhead-icons/fc-webicon-stumbleupon.svg'
file 'images/fairhead-icons/fc-webicon-tumblr-m.png'
file 'images/fairhead-icons/fc-webicon-tumblr-s.png'
file 'images/fairhead-icons/fc-webicon-tumblr.png'
file 'images/fairhead-icons/fc-webicon-tumblr.svg'
file 'images/fairhead-icons/fc-webicon-twitter-m.png'
file 'images/fairhead-icons/fc-webicon-twitter-s.png'
file 'images/fairhead-icons/fc-webicon-twitter.png'
file 'images/fairhead-icons/fc-webicon-twitter.svg'
file 'images/fairhead-icons/fc-webicon-vimeo-m.png'
file 'images/fairhead-icons/fc-webicon-vimeo-s.png'
file 'images/fairhead-icons/fc-webicon-vimeo.png'
file 'images/fairhead-icons/fc-webicon-vimeo.svg'
file 'images/fairhead-icons/fc-webicon-youtube-m.png'
file 'images/fairhead-icons/fc-webicon-youtube-s.png'
file 'images/fairhead-icons/fc-webicon-youtube.png'
file 'images/fairhead-icons/fc-webicon-youtube.svg'
file 'images/fairhead-icons/fc-webicon-youversion-m.png'
file 'images/fairhead-icons/fc-webicon-youversion-s.png'
file 'images/fairhead-icons/fc-webicon-youversion.png'
file 'images/fairhead-icons/fc-webicon-youversion.svg'
file 'images/fairhead-icons/fc-webicon-zerply-m.png'
file 'images/fairhead-icons/fc-webicon-zerply-s.png'
file 'images/fairhead-icons/fc-webicon-zerply.png'
file 'images/fairhead-icons/fc-webicon-zerply.svg'

file 'images/foundation/orbit/bullets.jpg'
file 'images/foundation/orbit/left-arrow-small.png'
file 'images/foundation/orbit/left-arrow.png'
file 'images/foundation/orbit/loading.gif'
file 'images/foundation/orbit/mask-black.png'
file 'images/foundation/orbit/pause-black.png'
file 'images/foundation/orbit/right-arrow-small.png'
file 'images/foundation/orbit/right-arrow.png'
file 'images/foundation/orbit/rotator-black.png'
file 'images/foundation/orbit/timer-black.png'

file 'javascripts/app.js'
file 'javascripts/foundation.min.js'
file 'javascripts/jquery.foundation.accordion.js'
file 'javascripts/jquery.foundation.alerts.js'
file 'javascripts/jquery.foundation.buttons.js'
file 'javascripts/jquery.foundation.clearing.js'
file 'javascripts/jquery.foundation.forms.js'
file 'javascripts/jquery.foundation.joyride.js'
file 'javascripts/jquery.foundation.magellan.js'
file 'javascripts/jquery.foundation.mediaQueryToggle.js'
file 'javascripts/jquery.foundation.navigation.js'
file 'javascripts/jquery.foundation.orbit.js'
file 'javascripts/jquery.foundation.reveal.js'
file 'javascripts/jquery.foundation.tabs.js'
file 'javascripts/jquery.foundation.tooltips.js'
file 'javascripts/jquery.foundation.topbar.js'
file 'javascripts/modernizr.foundation.js'

file 'languages/readme.txt'

file 'sass/_app.scss'
file 'sass/_settings.scss'

file 'stylesheets/fc-webicons.css'

# Wordpress Import
file '404.php'
file 'archive.php'
file 'category.php'
file 'comments.php'
file 'content-aside.php'
file 'content-image.php'
file 'content-link.php'
file 'content-none.php'
file 'content-page.php'
file 'content-quote.php'
file 'content-status.php'
file 'content.php'
file 'footer.php'
file 'functions.php'
file 'header.php'
file 'index.php'
file 'license.txt'
file 'loop.php'
file 'options.php'
file 'page.php'
file 'readme.txt'
file 'screenshot.png'
file 'search.php'
image 'search.png'
file 'searchform.php'
file 'sidebar.php'
file 'single.php'
file 'style.css'
file 'tag.php'

# Stylesheet Import
stylesheet 'editor-style.scss', :media => 'screen, projection'
stylesheet 'screen.scss', :media => 'screen, projection'
stylesheet 'print.scss', :media => 'screen, projection'
stylesheet 'ie.scss', :media => 'screen, projection', :condition => "lt IE 9"

# Compass Extension Help
help %Q{
    compass create -r wordpress-starter --using wordpress/foundation -s compressed foundation
}

# Compass Extension Welcome Message
# Users will see this when they create a new project using this template.
welcome_message %Q{
    This is a basic WordPress theme configured to use Foundation with Sass
}
